import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, company, service, message } = body;

    // Simple validation
    if (!name || !email || !company || !service) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      console.error("Missing RESEND_API_KEY environment variable");
      return NextResponse.json(
        { error: "Email service configuration is incomplete" },
        { status: 500 }
      );
    }

    // Call Resend REST API
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        from: "Vardhan Versatile <onboarding@resend.dev>",
        to: "vardhanversatile@gmail.com",
        subject: `New Inquiry from ${name} (${company})`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
            <h2 style="color: #0EA5A0; margin-top: 0;">New Contact Form Submission</h2>
            <p style="color: #475569; font-size: 16px;">You have received a new inquiry from your website portfolio.</p>
            <hr style="border: 0; border-top: 1px solid #f1f5f9; margin: 20px 0;" />
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px 0; color: #94a3b8; font-size: 14px; width: 120px;">Name:</td>
                <td style="padding: 8px 0; color: #0f172a; font-size: 14px; font-weight: bold;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; color: #94a3b8; font-size: 14px;">Email:</td>
                <td style="padding: 8px 0; color: #0f172a; font-size: 14px;"><a href="mailto:${email}" style="color: #0EA5A0; text-decoration: none;">${email}</a></td>
              </tr>
              <tr>
                <td style="padding: 8px 0; color: #94a3b8; font-size: 14px;">Company:</td>
                <td style="padding: 8px 0; color: #0f172a; font-size: 14px;">${company}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; color: #94a3b8; font-size: 14px;">Service:</td>
                <td style="padding: 8px 0; color: #0EA5A0; font-size: 14px; font-weight: bold;">${service}</td>
              </tr>
            </table>
            <hr style="border: 0; border-top: 1px solid #f1f5f9; margin: 20px 0;" />
            <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #f1f5f9;">
              <p style="color: #94a3b8; font-size: 12px; margin-top: 0; text-transform: uppercase; letter-spacing: 0.05em;">Message Details</p>
              <p style="color: #334155; font-size: 14px; line-height: 1.5; white-space: pre-wrap; margin-bottom: 0;">${message || "No message provided."}</p>
            </div>
            <p style="color: #94a3b8; font-size: 11px; text-align: center; margin-top: 30px;">This email was automatically generated by Vardhan Versatile website serverless function.</p>
          </div>
        `,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error("Resend API Error:", errorData);
      return NextResponse.json(
        { error: errorData.message || "Failed to send email" },
        { status: response.status }
      );
    }

    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error) {
    console.error("Server API Error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
